profile:
   default: novartis
   group:
     - [novartis, public]

project:
   type: book
   execute-dir: project
   pre-render: src/install_dependencies.R
   
   resources:
   - resources/**



execute:
   cache: true
   freeze: false

book:
  title: "Applied Modelling in Drug Development"
  subtitle: "Flexible regression modelling in Stan via `brms`"
  repo-actions: [issue]
  repo-branch: master
#  downloads: [pdf]
  output-file: bamdd
  author:
  - Sebastian Weber - <sebastian.weber@novartis.com>
  - Björn Holzhauer - <bjoern.holzhauer@novartis.com>
  - Lukas Widmer - <lukas_andreas.widmer@novartis.com>
  - Andrew Bean - <andrew.bean@novartis.com>
  date: today
  sidebar:
    logo: bamdd_logo.png

# we use per chapter references
bibliography:
  - src/references.bib
  - src/packages.bib

format:
  html:
    theme: 
    - cosmo
    - bamdd.scss
    css: bamdd.css
# embedding of resources would be desirable to avoid using google fonts, but deno does not
# work nice with the company SSL certificate setup
    embed-resources: false
#    code-fold: true
    code-tools: true
#    code-summary: "Show the code"
    source: repo
    html-math-method: 
      method: mathjax
      url: ./resources/mathjax/tex-mml-chtml.js
#    html-math-method: katex

#  pdf:
#    documentclass: scrreport
#    pdf-engine: xelatex
#    include-in-header:
#      - file: _macros.qmd # TODO: need to check how the macros can be include with a different format
#      - text: |
#         \usepackage{colortbl}
	  #  epub: default ## maybe enable this via the profiles feature in a production run only (takes time)
