project:
  output-dir: docs/public

book:
  repo-url: https://github.com/Novartis/bamdd/
  site-url: https://opensource.nibr.com/bamdd/
  chapters:
    - index.qmd
    - part: "Getting started"
      chapters:
      - src/01a_introduction.qmd
      - src/01b_basic_workflow.qmd
      - src/01c_priors.qmd
    - part: src/02_case_studies.qmd
      chapters:
      - src/02a_meta_analysis.qmd
      - src/02ab_meta_analysis_trtdiff.qmd
      - src/02ac_meta_analysis_strata.qmd
      - src/02l_single_arm_pos.qmd
      - src/02b_dose_finding.qmd
      - src/02c_dose_escalation.qmd
      - src/02cb_tte_dose_escalation.qmd
      - src/02e_multiple_imputation.qmd
      - src/02g_longitudinal.qmd
      - src/02h_mmrm.qmd
      - src/02i_time_to_event.qmd
      - src/02j_network_meta_analysis.qmd
    - part: "Advanced topics"
      chapters:
      - src/03a_stan_code.qmd
      - src/03b_parallel.qmd

format:
  pdf:
    documentclass: scrreport
    pdf-engine: xelatex
    include-in-header:
      - text: |
         \usepackage{colortbl}