---
format:
  html:
    author-title: "Editors"
---

# Preface {.unnumbered}

This website contains materials that were developed to accompany a series of 
workshops held in the Analytics department at Novartis over 2022-2024,
illustrating the utility of the R package `brms` for solving drug-
development problems. In order to highlight the versatility of that package,
we have developed a collection of case studies covering a diverse set of 
clinical questions that were addressed via Bayesian modelling with the `brms` package. 

::: {.content-visible when-profile="public"}
::: {.callout-tip}
## Courses in Paris (France), July 4<sup>th</sup> 20025, Göttingen (Germany), Dec 5/6<sup>th</sup> 2024 and at JSM (Portland, OR), Aug 5<sup>th</sup> 2024

Past course we offered recently:

1. Tutorial at the ["Stan4PMX
   workshop"](https://stan4pmx2025.sciencesconf.org).  
   [Slides](workshops/paris2025/slides/bamdd_paris2025.html), 
   [exercises](workshops/paris2025/exercises/bamdd_paris2025_exercises.html) &
   [additional material (see readme)](https://github.com/Novartis/bamdd/tree/main/workshops/paris2025)
2. A course at the workshop ["Hierarchical models in preclinical
   research"](https://www.biometrische-gesellschaft.de/arbeitsgruppen/bayes-methodik/workshops/2024-goettingen.html)
   of the IBS-DR working groups Non-clinical statistics and Bayes
   Methods on December 5/6<sup>th</sup>. The materials are available
   here:
   [Slides](workshops/goettingen2024/slides/bamdd_goettingen2024.html)
   & [additional material (see
   readme)](https://github.com/Novartis/bamdd/tree/main/workshops/goettingen2024)
3. A short course at the 2024 Joint Statistical Meetings in Portland
   on August 5<sup>th</sup>. The materials are available here:
   [Slides](workshops/jsm2024/slides/bamdd_jsm2024.pdf) & [additional
   material (see
   readme)](https://github.com/Novartis/bamdd/tree/main/workshops/jsm2024)

:::
:::

## Navigating the site

The material is organized as follows:

- @sec-introduction introduces `brms` and the objectives of these vignettes
- @sec-basic-workflow highlights the basic workflow (analysis steps and 
syntax) for carrying out an analysis with `brms`
- The next series of sections contain the case
studies. You can find a [listing with descriptions on this page](src/02_case_studies.qmd).
- Sections @sec-stan-code and @sec-parallel cover more technical topics, such
as exposing and injecting custom stan code to `brms` models,
and efficient parallel computation to support sampling in `brms`.


## Updates

This web-site is intended as a live document with updates as
appropiate. Key changes to the web-site are tracked here:



::: {.content-visible when-profile="public"}
- 13th January 2025: Linked materials from the course in Göttingen 
  in December 2024.
- 31st July 2024: Linked materials from JSM Portland 2024 short course
- 5th June 2024: Added @sec-pos on assessing probability of success of
  in Phase-III based on a single-arm trial in Phase-II
- 29th April 2024: Third edition course from Paul Bürkner with the new
  case studies on probability of success, meta-analytic priors with
  covariates & time-to-event modelling in Oncology phase I
  dose-escalation. Pre-read version.
- 19th April 2024: First public version at [opensource.nibr.com/bamdd](http://opensource.nibr.com/bamdd)
- 5th January 2024: Release web-site in more modern quarto book
  based format
- 26th April 2023: Second edition course from Paul Bürkner with the
  new case studies on MMRM, time-to-event data, surrogate endpoint
  meta-regression and network meta-analysis
- 27th April 2022: First release with course from Paul Bürkner
:::


::: {.content-visible when-profile="public"}
## License information

- The material on this website is provided under a CC BY 4.0 [license](https://github.com/Novartis/bamdd/tree/main/docs/public/LICENSE)
- The source code is provided under a GPL-2 [license](https://github.com/Novartis/bamdd/tree/main/LICENSE)
:::


